const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { chooseSettings, buildPrompt } = require('../native/codex.cjs');
const { encode, decoder } = require('../native/framing.cjs');
const { appendNote, validatePath, markdown } = require('../native/notes.cjs');
test.before(()=>fs.mkdir(path.resolve('.dev'),{recursive:true}));
const models = [{model:'regular',isDefault:true,defaultReasoningEffort:'medium',supportedReasoningEfforts:[{reasoningEffort:'low'},{reasoningEffort:'medium'}],serviceTiers:[]},
  {model:'gpt-test-luna',defaultReasoningEffort:'medium',supportedReasoningEfforts:[{reasoningEffort:'none'},{reasoningEffort:'medium'}],serviceTiers:[{id:'priority'}]}];
test('fast defaults to lightweight model and supported none/priority',()=>assert.deepEqual(chooseSettings(models),{model:'gpt-test-luna',effort:'none',serviceTier:'priority'}));
test('unsupported none and fast tier are not invented',()=>assert.deepEqual(chooseSettings(models,{model:'regular',fast:true}),{model:'regular',effort:'low',serviceTier:'default'}));
test('turning off fast mode preserves the independently chosen effort',()=>assert.deepEqual(chooseSettings(models,{model:'gpt-test-luna',effort:'none',fast:false}),{model:'gpt-test-luna',effort:'none',serviceTier:'default'}));
test('missing saved model is rejected',()=>assert.throws(()=>chooseSettings(models,{model:'missing'}),/不可用/));
test('prompt preserves multilingual source and bounds context',()=>{const input={selected:'こんにちは 🌏',nearby:'x'.repeat(9000),main:'y'.repeat(30000),title:'Test'};const output=JSON.parse(buildPrompt(input));assert.equal(output.selected,input.selected);assert.equal(output.nearby.length,5000);assert.equal(output.main.length,16000);});
test('oversized or empty selection is rejected',()=>{assert.throws(()=>buildPrompt({selected:'  '}));assert.throws(()=>buildPrompt({selected:'x'.repeat(12001)}));});
test('native protocol handles fragmented UTF-8 and multiple messages',()=>{const got=[];const errors=[];const read=decoder(m=>got.push(m),e=>errors.push(e));const data=Buffer.concat([encode({id:'a',text:'中文🌏'}),encode({id:'b'})]);for(let i=0;i<data.length;i+=3)read(data.subarray(i,i+3));assert.deepEqual(got,[{id:'a',text:'中文🌏'},{id:'b'}]);assert.equal(errors.length,0);});
test('native protocol rejects oversized frames',()=>{const b=Buffer.alloc(4);b.writeUInt32LE(1024*1024+1);let error;decoder(()=>assert.fail(),e=>error=e)(b);assert.match(error.message,/大小/);});
test('only absolute Markdown paths accepted',()=>{assert.throws(()=>validatePath('relative.md'));assert.throws(()=>validatePath(path.resolve('bad.exe')));if(process.platform==='win32'){assert.throws(()=>validatePath('C:\\file.md:payload'));assert.throws(()=>validatePath('\\\\server\\notes.md'));}assert.equal(validatePath(path.resolve('.dev/test.md')),path.resolve('.dev/test.md'));});
const record={selected:'sample ``` hostile\n<script>bad</script>',title:'Test\nPage',url:'https://example.com/',text:'## 翻译\n示例\n## 语境\n上下文',settings:{model:'test',effort:'low',serviceTier:'default'}};
test('saved source is fenced without allowing source fence escape',()=>{const md=markdown(record);assert.match(md,/````text/);assert.match(md,/Test Page/);assert.match(md,/https:\/\/example.com/);});
test('notes are appended without overwriting existing content',async()=>{const dir=await fs.mkdtemp(path.resolve('.dev/notes-test-'));const file=path.join(dir,'test.md');try{await fs.writeFile(file,'original');await appendNote(file,record);await appendNote(file,{...record,selected:'second'});const text=await fs.readFile(file,'utf8');assert.ok(text.startsWith('original'));assert.match(text,/second/);assert.equal((text.match(/## 翻译/g)||[]).length,2);}finally{await fs.rm(dir,{recursive:true});}});
test('hard-link note targets are refused',async()=>{const dir=await fs.mkdtemp(path.resolve('.dev/link-test-'));try{const original=path.join(dir,'original.md');const linked=path.join(dir,'linked.md');await fs.writeFile(original,'keep');await fs.link(original,linked);await assert.rejects(appendNote(linked,record),/链接/);assert.equal(await fs.readFile(original,'utf8'),'keep');}finally{await fs.rm(dir,{recursive:true});}});
